### ISSUE TITLE
Just testing

### ISSUE THREAD

**Issue by OnlySteveH** [krischery2150/Omega2150.v1#4]
I'm trying to get labels to work - it is proving _very_ frustrating.

**Comment by krischery2150** [comment]
I took the labels off the forms. You can turn them back on if you wish by just enabling label true, in forms.

**Comment by krischery2150** [comment]
I will turn them back on if you wish. Do you want me to do this for all the forms or?

**Comment by OnlySteveH** [comment]
I mean labelling issues in Github so we can see what's a database issue, what's an HTML layout issue, what's a CSS Styling issue, etc.

**Comment by krischery2150** [comment]
Ah got it. My knowledge is limited as far as this goes. If there is a way
to do it on github. I could do the research.

**Comment by OnlySteveH** [comment]
Yeah - it can be done on Github but it seems that only the project owner can assign a label to an issue?! 

So, I can create an issue (like this) but you have to assign a label to it. If you can raise my contributor status, that may be easier to manage ...

**Comment by krischery2150** [comment]
how do i that?

**Comment by OnlySteveH** [comment]
Not sure. Try going to the home page of the repository. 

Across the top of the page there's tabs for Code, Issues, Pull Requests - the last one is Settings. Click that. 

On the left there's a menu. The top one is Options. In there make sure Issues is ticked (in the Features section). Then go to Collaborators (on the left) - see if I'm in there as one. There may be some additional settings where you can amend the ability to change things? Not sure?

**Comment by krischery2150** [comment]
Should I transfer the ownership to you for the time being, thats the only
option correct?

**Comment by OnlySteveH** [comment]
No - you need ownership. 

I'll add suitable subject line rather than using labels.

**Comment by krischery2150** [comment]
Got it.

**Comment by OnlySteveH** [comment]
Was the Issues tick-box ticked?

**Comment by krischery2150** [comment]
Yes.  Thats what you are referring to correct?

**Comment by OnlySteveH** [comment]
OK. That's a generic setting across all repos. Github is a bit crap with collaboration, it would seem. If this proves to be a problem, we may be better moving over into Bitbucket. Firstly, Github repos are public, so anyone can see your code. You have to pay them to make the code private. Bitbucket do free private repos. I'd suggest that you don't want all your code being on public display?

**Comment by krischery2150** [comment]
yeah I am familiar with bitbucket.  I will make push the git there in a bit. What is your user name so that I can add you as a collaborator?

**Comment by OnlySteveH** [comment]
I'll be OnlySteveH - that's pretty much what I use everywhere!
